# These are supported funding model platforms

github: @Godmodes
patreon: @Godmodes
open_collective: @Godmodes
ko_fi: @Godmodes
tidelift: @Godmodes
community_bridge: @Godmodes
liberapay: @Godmodes
issuehunt: @Godmodes
otechie: @Godmodes
lfx_crowdfunding: @Godmodes
custom: @Godmodes
